apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: samplejava
  name: samplejava
spec:
  replicas: 3
  selector:
    matchLabels:
      run: samplejava
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: samplejava
    spec:
      containers:
      - image: kshamama/samplejava:latest
        name: samplejava
        ports:
        - containerPort: 8080
        resources: {}
status: {}
