apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplejava
spec:
  replicas: 3
  selector:
    matchLabels:
      run: samplejava
  template:
    metadata:
      labels:
        run: samplejava
    spec:
      containers:
      - image: kshamama/samplejava:1
        name: samplejava
        ports:
        - containerPort: 8080
