apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: samplejava
  name: samplejava
spec:
  containers:
  - image: kshamama/samplejava:1
    name: samplejava
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
