apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: samplejava
  name: samplejavalb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: samplejava
  type: LoadBalancer
status:
  loadBalancer: {}
